Lesson10
mfoxtrot/thinknetica_course pull request #1
Opened 2017-10-30 13:05 UTC by mfoxtrot

2017-10-30 17:18 UTC, vkurennov requested changes

2017-10-30 17:18 UTC, vkurennov commented on Lesson10/accessors.rb
> +          instance_variable_set("@#{arg}_history", [])
Здесь проблема есть: чтобы у тебя работала установка значений в историю в первый раз при вызове сеттера, тебе нужно уже проинициализированную переменную для истории. А инициализация будет выполнена только при первом вызове метода #{arg}_history. Получается, что надо обязательно в первый раз вызывать метод, чтобы все работало. Но код не должен иметь такие зависимости. Истоию и сеттер можно вызывать в любое время и в любом порядке.

2017-10-30 17:18 UTC, vkurennov commented on Lesson10/accessors.rb
> +      send("#{arg}_validate_class!")
Нет смысла делать метод для проверки, как и нет смысла вызывать его через send

2017-10-30 17:18 UTC, vkurennov commented on Lesson10/test.rb
> +puts "a_history = #{t.a_history}"
Убери эту строку и все сломается по причине, описанной выше.

2017-10-30 17:18 UTC, vkurennov commented on Lesson10/validation.rb
> +  @@validation_types = {
Это совершенно не нужно, наоборот, нам не надо задавать имена валидаций, главное ввести какое-то правило, что скажем, имя валидации соотвествует имени метода. Тогда валидации можно расширять, подключая новые методы.

2017-10-30 17:18 UTC, vkurennov commented on Lesson10/validation.rb
> +  @@to_validate = {}
Нельзя использовать переменные класса, потому что тогда любой подкласс сразу перезапишет валидации базового, и, что еще хуже, других подклассов. А валидации могут сильно отличаться. Поэтому тут только инстанс-переменные уровня класса, пусть и без наследования валидаций в подклассах.

2017-10-30 17:18 UTC, vkurennov commented on Lesson10/validation.rb
> +      method: @@validation_types[validation_type],
Почему не сохранять тип валидации так, как он указан при вызове метода?

2017-10-30 17:18 UTC, vkurennov commented on Lesson10/validation.rb
> +    define_method('validate!') do
Это и все остальные методы - это статические методы, поэтому define_method тут ни к чему. Раздели  это на 2 модуля для инстанс- и класс-методов и пропиши методы статически

2017-10-31 10:01 UTC, vkurennov requested changes

2017-10-31 10:01 UTC, vkurennov commented on Lesson10/accessors.rb
> +    define_method('initialize_history') do
Не нужно делать отдельного метода для инициализации. Это должно происходить автоматически в момент первого вызова геттера или сеттера

2017-10-31 10:01 UTC, vkurennov commented on Lesson10/test.rb
> +    initialize_history
Не должно быть никакого вызова для инициализации истории, это то же самое, что было, только "в профиль". У тебя по-прежнему класс зависит от какого-то спец. вызова. А должно быть так: подключил модуль, объявил атрибуты с историей, все работает без вызова спец. методов.

2017-10-31 10:01 UTC, vkurennov commented on Lesson10/validation.rb
> +    define_method('validate!') do
Зачем тут опять define_method? У метода имя динамическое? Или он зависит от каких-то переменных параметров? Нет. Это обычный статический метод, который берет данные из класса.

2017-10-31 20:22 UTC, mfoxtrot commented on Lesson10/accessors.rb
> +          instance_variable_set("@#{arg}_history", [])
Не согласен. Я ведь в 10 строке, прсваивая значение переменной @#{arg}_history, вызываю метод #{arg}_history, внутри которого и происходит инициализация. Поэтому вне зависимости от порядка вызова истории или сеттера, код будет работать. Или проблема в том, что такая "инициализация" проходит в неявном виде?

2017-11-01 06:52 UTC, vkurennov approved these changes

2017-11-01 06:52 UTC, vkurennov commented on Lesson10/accessors.rb
> +          instance_variable_set("@#{arg}_history", [])
Ага, вижу. Ну в принципе, тогда это рабочий вариант, хоть и не совсем явный. Ок. тогда замечание снимается

2017-11-01 08:07 UTC, merged